CREATE DATABASE TableRealtions
GO
USE TableRealtions
GO
CREATE TABLE Passports(
PassportID INT PRIMARY KEY NOT NULL,
PassportNumber VARCHAR(10) UNIQUE NOT NULL
)

CREATE TABLE Persons(
PersonID INT PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(20) NOT NULL,
Salary DECIMAL NOT NULL,
PassportID INT FOREIGN KEY REFERENCES Passports(PassportID)
)

INSERT INTO Passports(PassportID, PassportNumber) VALUES
(101, 'N34FG21B'),
(102, 'K65LO4R7'),
(103, 'ZE657QP2')

INSERT INTO Persons(FirstName, Salary, PassportID) VALUES
('Roberto', 43300.00, 102),
('Tom', 56100.00, 103),
('Yana', 60200.00, 101)